# ===================================
#  Reorder Behavior Config
# ===================================

# Reorder Title
title: profixs.forms::lang.system.labels.reorder_fields

# Attribute name
nameFrom: title

# Model Class name
modelClass: ProFixS\Forms\Models\Field

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: reorder_toolbar
